[package]
name = "kumo-dkim"
version = "0.3.0"
authors = ["Sven Sauleau <sven@cloudflare.com>"]
edition = "2021"
description = "DKIM (RFC6376) implementation"
repository = "https://github.com/cloudflare/dkim"
categories = ["email"]
keywords = ["email", "dkim", "authentification"]
readme = "README.md"
license = "MIT"

[features]
openssl = ["dep:openssl", "dep:openssl-sys", "dep:foreign-types"]
default = ["openssl"]

[dependencies]
base64 = "0.21.0"
chrono = { version = "0.4.26", default-features = false, features = ["clock", "std"] }
ed25519-dalek = {workspace=true, features=["pkcs8"]}
futures = {workspace=true}
indexmap = "1.9.3"
mailparsing = { path="../mailparsing" }
memchr = "2.5"
nom = "7.1.0"
once_cell = "1.17"
foreign-types = {version="0.3", optional=true}
openssl = { workspace=true, optional=true}
openssl-sys = { workspace=true, optional=true}
quick-error = "2.0.1"
rsa = "0.9"
sha-1 = { version = "0.10", features = ["oid"] }
sha2 = { version = "0.10", features = ["oid"] }
textwrap = "0.16"
tracing = "0.1"
hickory-resolver = {workspace=true}

[dev-dependencies]
criterion = "0.3"
k9 = "0.11"
regex = "1"
tokio = { workspace=true, features = ["macros"] }

[[bench]]
name = "sign"
harness = false
