[package]
name = "mod-kafka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = {path="../config"}
humantime-serde = "1.1"
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
rdkafka = "0.34"
serde = {version="1.0", features=["derive"]}
