[package]
name = "kumo-api-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = {version="0.4", default-features=false, features=["serde"]}
cidr-map = {path="../cidr-map"}
config = {path="../config"}
data-loader = {path="../data-loader"}
dns-resolver = {path="../dns-resolver"}
fancy-regex = "0.11"
humantime-serde = "1.1"
kumo-log-types = {path="../kumo-log-types"}
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
mod-memoize = {path="../mod-memoize"}
reqwest = {version="0.11", default-features=false, features=["json", "rustls-tls"]}
rfc5321 = {path="../rfc5321"}
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
toml = {version="0.7", features=["preserve_order"]}
tracing = "0.1"
spool = {path="../spool"}
throttle = {path="../throttle"}
url = "2.4"
utoipa = {workspace=true}
uuid = {workspace=true, features=["serde"]}

[dev-dependencies]
k9 = "0.11.6"
tokio = {workspace=true, features=["full"]}
